### PR TITLE
Add support for ESP32-C3

### PR DESCRIPTION
**Pull request by tjfsteele**

### CODE REVIEW

**Comment by tjfsteele** [comment]
There is also one change needed to esp async webserver  (separate lib) due to a compile error with ambigious overload:

return IPAddress(0U); ->  return IPAddress((uint32_t)0);

**Comment by DaveDavenport** [comment]
relevant issue: https://github.com/me-no-dev/ESPAsyncWebServer/issues/1164

**Comment by cpainchaud** [comment]
Can you please also make the change for the IPAddress(0U) code? and test it will still compile with other targets?
Then I will merge your request happily!

**Comment by cpainchaud** [comment]
You will also need to enable builds in .travis.platform.ini and add steps in the GitHub Actions (.github/workflows) so they get built automatically

**Comment by tjfsteele** [comment]
> Can you please also make the change for the IPAddress(0U) code? and test it will still compile with other targets? Then I will merge your request happily!

The other change is in a different Git repository, it's already been requested.

**Comment by tjfsteele** [comment]
If you can send me your postal address we would like to send you a pcb for RFlink32

**Comment by cpainchaud** [comment]
@tjfsteele me?

**Comment by tjfsteele** [comment]
> @tjfsteele me?

@cpainchaud Yes :)

**Comment by tjfsteele** [comment]
@cpainchaud My email address is nodo@tjfs.com

**Pull request merged**
