### PR TITLE
Fix AuriolV3 humidity decoding + add battery indicator

### PR DESCRIPTION
**Pull request by airy10**
My new RFLink32 install is picking some neighbours weather sensors as "Auriol V3" devices, but the humidity values are obviously wrong (> 100%)
rtl_433 is picking them as inFactory TH devices, with the same temp values, but correct humidity values (and with an additional battery indicator)
As it seems that they are really the same protocol, I've applied some changes from rtl_433 to the 044 plugin code (with some additional CRC check)
The problem was that the humidity is actually BCD encoded

Unfortunately, I don't have any "official" Auriol V3 device to check that RFLink "Auriol V3" is really the same as RTL_433 "inFactory TH"

### CODE REVIEW

**Comment by cpainchaud** [comment]
Let's give it a try!

Thank you for your contribution and please note that there is an RTL433 branch in this project which is looking for feedback :)

**Comment by airy10** [comment]
> Let's give it a try!
> 
> Thank you for your contribution and please note that there is an RTL433 branch in this project which is looking for feedback :)

I quickly tried it a few days ago. The rtl433 branch seems better on weather station, but doesn't get my RTL433 plug remote (while the main branch doesn't recognize the on/off part...). And I think that branch is missing the web server/OTA part ?  (or at least was crashing when trying to access that, which made experiments a bit more painful...)

**Comment by cpainchaud** [comment]
I issued potentials fixes on Friday for the 'crash'  which is working for me and another. Features should be on par with the main branch

**Comment by cpainchaud** [comment]
@airy10 the RTL433 branch yesterday has had new commits with even more RAM savings, make sure you use the latest of it, same for Obone's dependency library!

**Comment by airy10** [comment]
Latest RTL433 branch build seems stable

**Comment by airy10** [comment]
> @airy10 the RTL433 branch yesterday has had new commits with even more RAM savings, make sure you use the latest of it, same for Obone's dependency library!

Latest RTL433 branch build seems stable

**Pull request merged**
